export default{
    
    acknowledgmentLink:'[data-testid="nav-link-Acknowledgement"]',
    inboxLink:'[data-testid="nav-link-Inbox"]',
    meetingsLink:'(//a[@data-testid="nav-link-Meetings"])[2]',
    archivedLink:'[data-testid="nav-link-Archived"]',
    initialReviewTab:'//div[@title="Select Initial Review tab"]',
    acknowledgeTab:'[title="Select Acknowledge tab"]',
    finalReviewTab:'[data-testid="final_review"]',
    completeTab:'[title="Select Complete tab"]',
    selectAllOfDocumentName:'//span[text()="Document Name"]/..//preceding-sibling::th',
    documentDetailsBttn:'[title="Document Details"]',
    documentDownloadBttn:'[title="Document Download"]',
    selectApproveAcknowledgementRequired:'//label[text()="Approve – Acknowledgement Required"]/preceding-sibling::span',
    selectApproveNoAcknowledgement:'//label[text()="Approve – No Acknowledgement"]/preceding-sibling::span',
    selectReject:'//label[text()="Reject"]/preceding-sibling::span',
    submitBttn:'//button[text()="Submit"]',
    backToInboxBttn:'//button[text()="Back to Inbox"]',
    approvedQualityControlText:'//div[text()="Quality Control Review"]/following-sibling::div/div/div/text()',
    qualityControlText:'//div[text()="Quality Control Review"]/following-sibling::div/div/div/div/text()',
    documentInTheList:'//tbody/tr/td[2]/div',
    headingText:'//h2',
    DocumentList:'//tbody/tr',
    seacrhDocuments:'[placeholder="Search documents"]',
    noOfRowsPerPageDropDown:'[placeholder="Select an option"]',
    listColumnName:'//span[@class="relative"]/text()',
    tabHeadingText:'//div[@class="subtitle mb-4 md:mb-0 md:mr-2"]/text()',
    archicveBttn:'[data-icon="archive"]',
    moveToInboxBttn:'//button[text()="Move to inbox"]',
    startQcBttnOfFirstDocument:'//tbody/tr[1]/td[6]/button[text()="Start QC"]',
    documentStatusDropdown:'//input[@value="All Document Statuses"]',
    completedStatus:'//div/ul/li/span[text()="Completed"]',
    viewButtonOfFirstDocument:'//tbody/tr[1]/td[last()-1]/button[text()="View"]',
    selectFirstDocument:'//tbody/tr[1]/td[1]',

}