export default {
    eSignBttn: '[data-testid="nav-link-eSign"]',
    createNeweSignBttn:'//button[text()="Create new eSign"]',
    packetTitlTxtBx:"[name='packetTitle']",
    packetTitle:'[class="inline-flex items-center input-with-pencil max-w-full"]',
    nextBttn:"(//button[text()='Next'])[1]",
    uploadDocumentsBttn:'#upload-document-',
    saveAndExitBttn:'//*[text()="Save and exit"]',
    selectJustOthersBttn:"[title='Select Just others']",
    selectJustMeAndOthersBttn:"[title='Select Me & others']",
    selectJustMeBttn:"[title='Select Just me']",
    barsIcon:"[data-icon='bars']",
    trashIcon:"[data-icon='trash']",
    addSignerBttn:'//*[text()=" Add signer"]',
    addSignerButton:'//*[text()="+ Add signer"]',
    firstNameOfSignerTxtBx:'(//input[@data-field-name="firstName"])[last()]',
    middleNameOfSignerTxtBx:'(//input[@data-field-name="middleName"])[last()]',
    lastNameOfSignerTxtBx:'(//input[@data-field-name="lastName"])[last()]',
    emailOfSignerTxtBx:'(//input[@data-field-name="email"])[last()]',
    backBttn:'//button[text()="Back"]',
    reviewPacketDetaisBttn:'//button[text()="Review packet details"]',
    markReadyForSigningBttn:'//div[text()="Mark Ready for Signing"]',
    selectAssigneeDropDown:"[placeholder='Select an option']",
    createdByDropdown:'[placeholder="Created by"]',
    fullNameAnnotation:"//b[text()='Full Name']",
    signatureAnnotation:"//b[text()='Signature']",
    initialsAnnotation:"//b[text()='Initials']",
    dateAnnotation:"//b[text()='Date']",
    textFieldAnnotation:"//b[text()='Text Field']",
    checkBoxAnnotation:"//b[text()='Checkbox']",
    deleteAllAnnotationsBttn:"//b[text()='Delete all annotations']",
    dataHiddenBttn:"[data-icon='angle-double-left']",
    applyExisitingTemplateBttn:'[data-testid="apply-existing-template"]',
    reassignAnnotationDropdown:'[placeholder="Reassign annotation"]',
    smallBtnn:"//div[text()='sm']",
    mediumBtnn:"//div[text()='md']",
    largeBtnn:"//div[text()='lg']",
    maximizeBtnn:'[data-icon="plus-circle"]',
    minimizeBtnn:'[data-icon="minus-circle"]',
    backtoPacketDetailsLink:'//*[text()="Back to packet details"]',
    makeChangesBtnn:"//div[text()='Make Changes']",
    eSigncloseBtnn:"[data-icon='times']",
    setSigningOrderCheckBx:'[title="Set signing order"]',
    pencilIconBtnn:'[data-icon="pencil"]',
    eSignTitleTxtBx:'[placeholder="Enter value"]',
    cancelBtnn:"//button[text()='Cancel']",
    saveAndSignNow:'//button[text()="Save & Sign now"]',
    emailMessageTxtBx:'[name="Email message"]',
    addDocument:'//button[text()="+ Add documents"]',
    uploadButton:'//button[text()="Upload"]',
    firstSigner:'(//span/*[@data-icon="ellipsis-h"])[1]',
    secondSigner:'(//span/*[@data-icon="ellipsis-h"])[2]',
    thirdSigner:'(//span/*[@data-icon="ellipsis-h"])[3]',
    sendInvite:'//span[text()="Send Invite"]',
    editBttn:'//span[text()="Edit"]',
    deleteBttn:'//span[text()="Delete"]',
    docEditButton:'(//*[@data-icon="ellipsis-h"])[2]',
    viewDocumentBttn:'//li/span[text()="View Document"]',
    editAnnotationsBttn:'//span[text()="Edit Annotations"]',
    removeDocument:'//span[text()="Remove Document"]',
    removeDocumentBttn:'//button[text()="Remove "]',
    saveBttn:'//button[text()="Save"]',
    saveExitButton:'//button[text()="Save & "]',
    verifyPacketInTheList:'(//tbody/tr[1]/td)[1]',
    removeSignerBttn:"//button[text()='Remove ']",
    signerEditBttn:'//div/span[text()="manasa.lingala@qualitlabs.com"]/following-sibling::span/div[1]',
    editFirstName:'//input[@data-field-name="first_name"]',
    editMiddleName:'//input[@data-field-name="middle_name"]',
    editLastName:'//input[@data-field-name="last_name"]',
    editEmail:'//input[@data-field-name="email"]',
    eSignStatusIneSignPage:"//tr[1]/td[2]//text()",
    packetStatusInEsignDetailsPage:'(//div[2]/text())[2]',
    saveAndSendNow:'//button[text()="Save & Send now"]',
    viewPacketDetailsBttn:'//button[text()="View packet details"]',
    doneBttn:'//button[text()="Done"]',
    packetStatusInTheList:'//tr[1]/td[4]/div/text()',
    packetTitleIneSignDetailsPage:'//h3/div/text()',
    eSignLink:'//span[text()="eSign"]',
    cancelPacketBttn:'//button[text()="Cancel packet"]',
    cancelPacketBttn2:'(//button[text()="Cancel packet"])[2]',
    searchPacketTxBx:'[placeholder="Search"]',
    addedDocName:'(//table/tbody/tr)[last()]/td[1]/text()',
    statusDropdown:'[placeholder="Packet status"]',
    valueOfDropdown:'//div/ul/li/span/text()',
    packetDetailsPage:'//div/span[3][text()="Packet Details"]',
    editSignerButton:'(//div[text()="Signers"]/../following-sibling::div/div/span[2]/div/div/div)[1]',
    signerMailOfEditButton:'(//div[text()="Signers"]/../following-sibling::div/div/span/text()[3])[1]',
    uploadDocInESignDetailsPage:"//div[@data-testid='drop-target']//label[1]",
    editDocumentButton:'//div[text()="Documents"]/../following-sibling::div/div/table/tbody/tr/td[4]/div',
    documentName:'//div[text()="Documents"]/../following-sibling::div/div/table/tbody/tr/td[1]/text()',
    documentList:'//tbody/tr/td[1]',
    packetTitleEditBttn:'//h3/div/span/*',
    editPacketTitleTxBx:'[name="Editable input"]',
    eSignHeading:'//h2/text()',
    tabSubtitle:'//div/div[@class="subtitle mb-6"]',
    eSignListColoumnName:'//thead/tr/th/span/text()',
    previousBttn:'[data-pager="previous"]',
    nextButton:'[data-pager="next"]',
    errorText:'//p[@class="text-danger text-right"]',
    emailValidationError:'//p[@data-testid="email-validation-error"]',
    inputValidationError:'//p[@data-testid="stavviz-input-validation-error"]',
    resendInvite:'//div//li[@title="Resend Invite"]',
    sendBttn:'//button[text()="Send"]',
    inviteAllSigners:'//button[text()="Invite all signers"]',
    saveIconBttn:'[data-icon="check"]',
    signNowBttn:'//button[text()="Sign now"]',
    startSigning:'//button[text()="Start Signing"]',
    finishSigning:'//button[text()="Finish signing"]',
    completeSigning:'//*[text()="Signing Complete"]',
    documentSignedText:'//span[@data-testid="esign-document-signed-banner"][text()="Document has been signed."]',
    signerDropdown:'[placeholder="Signer"]',
    applyBttn:'//button[text()="Apply"]',
    annotationsToSign:'//div[@class="cursor-pointer react-draggable"]',
    useThisSignatureBttn:'//button[text()="Use this signature"]',
    packetTitleInViewDocument:'//div/div[@class="subtitle mb-6"]/text()',
    documentNameInViewDocument:'//div[@class="text-sm mb-6"][1]',
    loadedDocument:'//div[@class="react-pdf__Page"]',
    startSigningLink:'//span[text()="Start signing"]',
    editAnnotationsBttnInViewDocument:'//button[text()="Edit Annotations"]',
    addSignersBttnInViewDocument:'//button[text()="Add Signers"]',
    editButtonOfSignerInViewDocumentPage:"//div[@role='button']//div[1]",
    backToPacketOverviewLink:'//div[@data-testid="back-button"]',
    backToSignerPortal:'//div[@data-testid="back-button"]',
    packetDetailsBttnInSignerPortal:'[title="Packet Details - Click to open"]',
    signYourDocumentsText:'//h2[text()="Sign your documents"]',
    viewYourSignedDocumentsText:'//h2[text()="View your signed documents"]',
    signerPortalHeading:'//h1[text()="Signer Portal"]',
    eSignPacketsTabInSignerPortal:'[title="Select eSign Packets tab"]',
    meetingsTabInSignerPortal:'[title="Select Meetings tab"]',
    checkBoxInAdopNewSignature:'//div[@title="I consent to the use of electronic signatures and records."]/span/span',

}