export default {
    eSignBttn: '[data-testid="nav-link-eSign"]',
    createNeweSignBttn:'//*[text()="+ Create New eSign"]',
    packetTitlTxtBx:"[name='packetTitle']",
    packetTitle:'[class="inline-flex items-center input-with-pencil max-w-full"]',
    nextBttn:"//*[text()='Next']",
    uploadDocumentsBttn:'#upload-document-',
    saveAndExitBttn:'//*[text()="Save and exit"]',
    selectJustOthersBttn:"[title='Select Just others']",
    selectJustMeAndOthersBttn:"[title='Select Me & others']",
    selectJustMeBttn:"[title='Select Just me']",
    barsIcon:"[data-icon='bars']",
    trashIcon:"[data-icon='trash']",
    AddSignerBttn:'//*[text()=" Add signer"]',
    addSignerBttn:'//*[text()="+ Add signer"]',
    firstNameOfFirstSignerTxtBx:'(//*[@data-field-name="firstName"])[1]',
    middleNameOfFirstSignerTxtBx:'(//*[@data-field-name="middleName"])[1]',
    lastNameOfFirstSignerTxtBx:'(//*[@data-field-name="lastName"])[1]',
    emailOfFirstSignerTxtBx:'(//*[@data-field-name="email"])[1]',
    firstNameOfSecondSignerTxtBx:'(//*[@data-field-name="firstName"])[2]',
    middleNameOfSecondSignerTxtBx:'(//*[@data-field-name="middleName"])[2]',
    lastNameOfSecondSignerTxtBx:'(//*[@data-field-name="lastName"])[2]',
    emailOfSecondSignerTxtBx:'(//*[@data-field-name="email"])[2]',
    backBttn:'//*[text()="Back"]',
    reviewPacketDetaisBttn:'//*[text()="Review packet details"]',
    markReadyForSigningBttn:'//*[text()="Mark Ready for Signing"]',
    selectAssigneeDropDown:"[placeholder='Select an option']",
    fullNameAnnotation:"//*[text()='Full Name']",
    signatureAnnotation:"//*[text()='Signature']",
    initialsAnnotation:"//*[text()='Initials']",
    dateAnnotation:"//*[text()='Date']",
    textFieldAnnotation:"//*[text()='Text Field']",
    checkBoxAnnotation:"//*[text()='Checkbox']",
    deleteAllAnnotationsBttn:"//*[text()='Delete all annotations']",
    dataHiddenBttn:"[data-icon='angle-double-left']",
    applyExisitingTemplateBttn:'[data-testid="apply-existing-template"]',
    reassignAnnotationDropdown:'[placeholder="Reassign annotation"]',
    smallBtnn:"//*[text()='sm']",
    mediumBtnn:"//*[text()='md']",
    largeBtnn:"//*[text()='lg']",
    maximizeBtnn:'[data-icon="plus-circle"]',
    minimizeBtnn:'[data-icon="minus-circle"]',
    backtoPacketDetailsLink:'//*[text()="Back to packet details"]',
    makeChangedBtnn:"//*[text()='Make Changes']",
    eSigncloseBtnn:"[data-icon='times']",
    setSigningOrderCheckBx:'[title="Set signing order"]',
    pencilIconBtnn:'[data-icon="pencil"]',
    eSignTitleTxtBx:'[placeholder="Enter value"]',
    cancelBtnn:"//*[text()='Cancel']",
    saveAndSignNow:'//*[text()="Save & Sign now"]',
    emailMessageTxtBx:'[name="Email message"]',
    //PacketName:'//*[text()="'+eSignpacketName +'"]',
    addDocument:'//*[text()="+ Add documents"]',
    uploadButton:'//*[text()="Upload"]',
    firstSigner:'(//*[@data-icon="ellipsis-h"])[1]',
    secondSigner:'(//*[@data-icon="ellipsis-h"])[2]',
    thirdSigner:'(//*[@data-icon="ellipsis-h"])[3]',
    sendInvite:'//*[text()="Send Invite"]',
    editBttn:'//*[text()="Edit"]',
    deleteBttn:'//*[text()="Delete"]',
    docEditButton:'(//*[@data-icon="ellipsis-h"])[2]',
    viewDocumentBttn:'//*[text()="View Document"]',
    editAnnotationsBttn:'//*[text()="Edit Annotations"]',
    removeDocument:'//*[text()="Remove Document"]',
    removeDocumentBttn:'//*[text()="Remove "]',
    saveBttn:'//*[text()="Save"]',
    saveAndExitButton:'//*[text()="Save & Exit"]',
    verifyPacketInTheList:'(//*/tbody/tr[1]/td)[1]',
    removeSignerBttn:"//*[text()='Remove ']",
    signerEditBttn:'//div/span[text()="manasa.lingala@qualitlabs.com"]/following-sibling::span/div[1]',
    editFirstName:'//*[@data-field-name="first_name"]',
    editMiddleName:'//*[@data-field-name="middle_name"]',
    editLastName:'//*[@data-field-name="last_name"]',
    editEmail:'//*[@data-field-name="email"]',
    eSignStatusIneSignPage:"//tr[1]/td[2]//text()",
    packetStatusInEsignDetailsPage:'(//*/div[2]/text())[2]'

}