export default {
    createMeetingBttn: "[class=align-bottom]",
    meetingsLink:'(//a[@data-testid="nav-link-Meetings"])[1]',
    purchaseTypeBttn:'//span[text()="Purchase"]',
    refinanceTypeBtnn: "//span[text()='Refinance']",
    equityTypeBtnn:"//span[text()='Equity']",
    modificationTypeBtnn:"//span[text()='Modification']",
    propertyAddressTextbx : '[placeholder="Property Address Search"]',
    meetingDate: '[placeholder="MM/DD/YYYY"]',
    startTime: '(//input[@name="timezone-dropdown"])[1]',
    timeZone: '(//input[@name="timezone-dropdown"])[2]',
    defaultTimeZoneText:'[placeholder="Select timezone"]',
    notary: '[name="notary"]',
    fisrtnameTxtbx:'[data-testid="firstName"]',
    middleNameTxbx:'[data-testid="middleName"]',
    lastNameTxtbx: '[data-testid="lastName"]',
    phoneNumberTxtbx: '(//input[@inputmode="numeric"])[last()]',
    emailTxtbx:'[data-testid="email"]',
    createClosingBttn: "(//button[contains(text(),'Create')])[last()]",
    firstNameInAddAttendee:'(//input[@placeholder="First Name"])[last()]',
    middleNameInAddAttendee:'(//input[@placeholder="Middle Name"])[last()]',
    lastNameInAddAttendee:'(//input[@placeholder="Last Name"])[last()]',
    emailInAddAttendee:'(//input[@placeholder="Email"])[last()]',
    streetName: '[name="Street name"]',
    streetNumber: '[name="Street no."]',
    city:'[name="City"]',
    postalCode: '[name="ZIP Code"]',
    addressUnit:'[name="Unit/Apt"]',
    closingsBttn:"//*[text()='Closings']",
    closingDetailsPage:'//span[3]/text()',
    fileNumberTxBx:"[name='fileNumber']",
    fileId:'//div[3]/div/div[2]/text()',
    closingsLink:'//*[text()="Closings"]',
    scheduledMeetingsBttn:'//div[text()="Scheduled"]',
    completedMeetingsBttn:'//div[text()="Completed"]',
    cancelledMeetingsBttn:'//div[text()="Cancelled"]',
    meetingsHeading:'//h2/text()',
    meetingCardStatus:'(//*[@data-testid="meeting-card"]/div[2]/div/div[1]/span)[1]',
    filterByNotaryDropdown:'[placeholder="My meetings"]',
    addDocumentBttn:'//button[text()="+ Add document"]',
    addAttendeeBttn:'//button[text()="+ Add attendee"]',
    addAttendeeBttnInMeetingInfoPage:'//button[text()="Add attendee"]',
    uploadDocumentField:'#upload-doc',
    uploadButton:'//button[text()="Upload"]',
    documentName:'((//tbody)[2]/tr[last()]//td/div/div/text())[1]',
    addedAttendeeEmail:'(//tbody)[1]/tr/td[3]/text()',
    addedAttendeeName:'(//tbody)[1]/tr/td[1]/text()',
    transactionType:'//div[@class="text-base"][2]/text()',
    addressTextInMeetingDetailsPage:'//h3/div/text()',
    nextArrowButton:'[data-icon="long-arrow-right"]',
    loanNumberInList:'//div/div[1]/div[1][@class="flex flex-row"]/p[2]/text()',
    meetingCardInList:'//div[@data-testid="meeting-card"][1]',
    firstMeetingLoanNumber:'(//div/div[1]/div[1][@class="flex flex-row"]/p[2]/text())[1]',
    createNewPageText:'//div[@role="button"]/div/div',
    closingMeetingBttn:'//div[@role="button"]/div/div[text()="Closing Meeting"]',
    selectAttendeeTypeDropdown:'[placeholder="Select an option"]',
    observerAttendeeType:'[title="Observer"]',
    editBttn:'//span[text()="Edit"]',
    firstNameInEditSigner:'[placeholder="First name"]',
    middleNameInEditSigner:'[placeholder="Middle name"]',
    lastNameInEditSigner:'[placeholder="Last name"]',
    emailInEditSigner:'[placeholder="Email"]',
    saveButton:'//button[text()="Save"]',
    resendInviteBttn:'//li/span[text()="Resend invite"]',
    moreActionsBttn:'//button[text()="More actions"]',
    cancelBttn:'//li/span[text()="Cancel"]',
    meetingCardStatusInMeetingDetailsPage:'//div[@data-testid="meeting-detail-card"]/div/div/text()',
    joinButton:'[data-testid="meeting-join-btn"]',
    meetingType:'[name="meeting-type"]',
    nextBttn:'//button[text()="Next"]',
    signingMeetingBttn:'//div[text()="Signing Meeting"]',
    errorText:'//*[@class="error-text"]/text()',
    addObserverBttn:"//button[text()='Observer']",
    prepareForEsigningLink:'//span[text()="Prepare for eSigning"]',
    markReadyForSigningBttn:'//div[text()="Mark Ready for Signing"]',
    backToMeetingDetailsLink:'//div[text()="Back to meeting detail"]',
    documentStatusInEditDocumentPage:'//div[@class="text-sm uppercase w-full mb-6"]/div/text()',
    editDocumentLink:'//span[text()="Edit Document"]',
    makeChangesBttn:'//div[text()="Make Changes"]',
    emailValidationErrorMessage:'[data-testid="email-input-signer-validation-error"]',
    addExternalNotaryBttn:"//button[contains(text(),'Add external notary')]",
    addNotaryBttn:'//button[text()="Add Notary"]',
    notaryEmail:'[placeholder="Notary email"]',
    notaryFirstName:'[placeholder="Notary first name"]',
    notaryMiddleName:'[placeholder="Notary middle name (optional)"]',
    notaryLastName:'[placeholder="Notary last name"]',
    inviteNotaryBttn:'//button[text()="Invite Notary"]',
    externalNotaryNameInCreateMeetingPage:'//div[@class="mt-2"]/text()[2]',
    viewVerificationResultsBttn:'//li/span[text()="View verification results"]',
    signerNameInVerificationResultPage:'//div[@class="modal-header"]/text()[1]',
    securityDetailsTxt:'//div[@class="modal-header"]/text()[2]',
    KBAheading:'//div[@class="audit-log"]/h4[1]/text()',
    scansHeading:'//div[@class="audit-log"]/h4[2]/text()',
    archiveBttn:"//span[@title='Archive']",
    unarchiveBttn:'span[title="Unarchive"]',
    editButtonOfNotary:'//tbody/tr/td[2][text()="Notary"]/../td[last()]/div/div/div',
    reassignBttn:'//li/span[text()="Reassign"]',
    reassignBttnInReassignNotaryPage:'//button[text()="Reassign"]',
    myMeetingsDropdown:'[placeholder="My meetings"]',
    selectAllBttn:'[title="Select All"]',
    editFileIdButton:'//div[3]/div/div[2]/span/*',
    fileIdNumberTxBx:'[placeholder="ID Number"]',
    saveIconButton:'[data-icon="check"]'
}