export default{
    ordersBttnInSidebar:'[data-testid="nav-link-Orders"]',
    originationOrdersBttnInSidebar:'[data-testid="nav-link-Origination"]',
    servicingOrdersBtnnInSidebar:'[data-testid="nav-link-Servicing"]',
    pendingOrdersTab:'[title="Select Pending tab"]',
    inProgressOrdersTab:'[title="Select In Progress tab"]',
    favoritesOrdersTab:'[title="Select Favorites tab"]',
    archivedOrdersBttn:'[data-testid="inbox-"]',
    completedOrdersTab:'[data-testid="completed"]',
    readyOrdersTab:'[title="Select Ready tab"]',
    createOrderBttn:'//button[text()="Create order"]',
    fileNameInTheList:'//div[@class="table-body"]/div/div/div[1]/text()',
    pageHeading:'//h2/text()',
    OrdersTabSubtitle:'//div[@class="subtitle mb-6"]/text()',
    noOfRowsDropDown:'[placeholder="Select an option"]',
    ordersSearchBar:'[class="search-text w-full"]',
    ordersList:'//tbody/tr',
    orderDetailspage:'//div[@class="text-sm"]/span[3]',
    loanNumberInTheDetailsPage:'//div[text()="Loan Number"]/../text()',
    assignedOrdersLinkInOrderDetails:'//span[text()="Assigned Orders"]',
    cancelItBttn:'//button[text()="Yes, cancel it"]',
    orderStatusInTheList:'//div[@class="table-body"]/div/div/div[8]',
    orderTypeInTheList:'//tbody/tr[1]/td[4]/text()',
    fileNameInTheList:'//tbody/tr[1]/td[1]/text()',
    fileInTheList:'//tbody/tr[1]',
    markCompleteButton:'[title="Mark complete"]',
    cancelButton:'[title="Cancel"]',
    }
    