export default
{
organizationsLink:'[data-testid="nav-link-Organizations"]',
inviteNewVendorBttn:"(//button[contains(text(),'Invite vendor')])[1]",
vendorDomainTxBx:'[placeholder="Website"]',
nextBttn:'//button[text()="Next"]',
backBttn:'//button[text()="Back"]',
closeIcon:'[data-icon="times"]',
vendorNameTxBx:'[placeholder="Vendor name"]',
firstNameTxBx:'[placeholder="First name"]',
middleNameTxBx:'[placeholder="Middle name"]',
lastNameTxBx:'[placeholder="Last name"]',
emailTxBx:'[placeholder="Email"]',
inviteVendorBttn:"(//button[contains(text(),'Invite')])[2]",
errorText:'//p[@class="error-text"]/text()',
domainTxt:'//tr/td[1]/span[2]/text()',
details:'(//tr/td[4]/span[text()="DETAILS"])[1]',
websiteNotAvailableBttn:'//button[text()="Website not available"]',
vendorPhoneNumberTxBx:'[inputmode="numeric"]',
}