export default {
usersBttn: '[data-testid="nav-link-Users"]',
inviteUserBttn: "[data-testid='open-invite-modal-btn']",
firstNameTxtbx: "[name='first-name']",
middleNameTxbx: "[name='middle-name']",
lastNameTxbx:   "[name='last-name']",
emailTxbx: "[name='email']",
roleDropdownBttn: "[placeholder='Role']",
adminRoleBttn: "[title='Admin']",
userRoleBttn: "[title='User']",
notaryCheckbx: "(//div[contains(@class,'h-8 text-sm')]//span)[2]/*",
addUserBttn: "//*[text()='+ Add user']",
inviteUsersBttn: "[data-testid='invite-users-btn']",
deleteUserBttn:'//*[text()="Delete User"]',
manageUserCloseBttn: "[class='close']",
errorText:"[class='error-text']",
pageNumber:'//div[2]/span/text()',
searchUser:'[placeholder="Search users"]',
userStatus:'(//td[2]/p/text())',
notaryCheckBox:'[type="checkbox"]',
userRole:'//input[@value="User"]',
filterByNotaryBttn:'//input[@placeholder="My meetings"]',
adminUser:'(//td/p[text()="Admin"])[1]',
user:'//tr/td[1]',
user:'(//td/p[text()="User"])[1]',
selectRoleDropDown:'[placeholder="Select role"]',
saveUserBttn:'//button[text()="Save User"]',
createLoanOfficerBttn:"//button[contains(@class,'stavviz-button rounded')]/following-sibling::button[1]",
loanOfficerName:'[placeholder="Name"]',
laonOfficerEmail:'[placeholder="Email"]',
loanOfficerPhone:'[placeholder="Phone"]',
NMLSlicesnceNumber:'[placeholder="NMLS License Number"]',
submitBttn:'//button[text()="Submit"]',
userNameInTheList:'//div[@class="user-name"]'
}