import selectors from '../Selectors/orders';
export class Orders{

    navigateToAssignedOrders(){
      cy.get(selectors.assignedOrderBttnInSideBar).click();
    }
    navigateToPendingOrders()
    {
        cy.get(selectors.pendingBttn).click();
        cy.wait(4000);
    }
    navigateToInProgressOrders()
    {
        cy.get(selectors.inProgressBttn).click();
    }
    navigateToMyFavoritesOrders()
    {
        cy.get(selectors.myFavoritesBttn).click()
    }
    clickOnArchivedButton()
    {
        cy.get(selectors.archivedOrdersBttn).click();
    }
    navigateToCompletedOrders()
    {
        cy.get(selectors.completedOrdersBttn).click();
    }
    acceptOrRejectOrderByNameAndType(fileName,OrderType,action)
    {
        cy.xpath('//div[@class="table-body"]/div/div/div[1][text()="'+fileName+'"]/following-sibling::div[text()="'+OrderType+'"]/following-sibling::div/div/button[text()="'+action+'"]').click();
    }
    verifyOrderTypeInTheList(file,type)
     {
         cy.xpath('//div[@class="table-body"]/div/div/div[1][text()="'+file+'"]/following-sibling::div[4]').should('have.text',type);
     }
     verifyOrderStatusInTheList(file,status)
     { 
         cy.xpath('//div[@class="table-body"]/div/div/div[1][text()="'+file+'"]/following-sibling::div[7]').should('have.text',status)
     }
     verifyOrderInTheList(file)
     {
         cy.xpath(selectors.fileNameInTheList).should('contain.text',file)
     }
     verifyOrderNotPresentInTheList(file,orderType)
     {
         cy.xpath('//div[@class="table-body"]/div/div/div[1][text()="'+file+'"]/following-sibling::div[4][text()="'+orderType+'"]').should('not.exist')
     }
     verifyOrderDetailsInTheList(file,type,status)
     {
         this.verifyOrderInTheList(file);
         this.verifyOrderTypeInTheList(file,type);
         this.verifyOrderStatusInTheList(file,status);
     }
     verifyPageHeading(heading)
     {
         cy.xpath(selectors.pageHeading).should('have.text',heading)
     }
     navigateToOrderDetailsPage(file)
     {
         cy.xpath('(//div[@class="table-body"]/div/div/div[1][text()="'+file+'"])[1]').click();
     }
     verifyFileNameInTheDetailsPage(loanNumber)
     {
         cy.xpath(selectors.loanNumberInTheDetailsPage).should('contain.text',loanNumber)
     }
     verifyOrderStatusInOrderDetails(orderType,status)
     {
         cy.xpath('//div[text()="'+orderType+'"]/../following-sibling::div/div/div/div/div').should('have.text',status)
     }
     verifyNavigatedToOrderDetailsPage()
    {
        cy.xpath(selectors.orderDetailspage).should('have.text',"Order Details");
    }
    navigateToOrdersListThroughAssignedOrdersLink()
    {
        cy.xpath(selectors.assignedOrdersLinkInOrderDetails).click();
    }
    verifyOrderDetailsInTheDetailsPage(file,orderType,status)
    {
       this.verifyNavigatedToOrderDetailsPage();
       this.verifyFileNameInTheDetailsPage(file);
       this.verifyOrderStatusInOrderDetails(orderType,status);
    }
    acceptOrRejectOrderInDetailsPage(orderType,action)
    {
        cy.xpath('//div[text()="'+orderType+'"]/../following-sibling::div/div[5]/button[text()="'+action+'"]').click();
    }
    clickCancelItButton()
    {
        cy.xpath(selectors.cancelItBttn).click();
    }
    verifystatusOfOrdersInTheList(status)
    {
        cy.xpath(selectors.orderStatusInTheList).should('contain.text',status);
    }
    
    }
